import {
  GOOGLE_CLIENT_ID_ANDROID,
  GOOGLE_CLIENT_ID_WEB,
  SUPABASE_ANON_KEY,
  SUPABASE_URL,
} from '@env';

const envConfig = {
  SUPABASE_ANON_KEY,
  SUPABASE_URL,
  GOOGLE_CLIENT_ID_ANDROID,
  GOOGLE_CLIENT_ID_WEB,
};

export default envConfig;
